# This file contains all the configuration settings to run
# an import job to the datEAUbase using the Import.py script.
# Paths need to be entered relative to the script's location on the file system.
#
database_config:
  database_name: dateaubase2020
  credentials_path: ../../secrets.yaml
  local_url: GCI-PR-DATEAU02\\DATEAUBASE
  remote_url: 132.203.190.77\\DATEAUBASE

file_configs:
  -
    name: rodtox
    file_structure:
      separator: ;
      encoding: UTF-8
      dt_format: "%d.%m.%Y %H:%M:%S"
      time_column: TimeString
      timezone: US/Eastern
      value_column: VarValue
      variable_column: VarName
      validity_column: Validity
      validity_flag: 1
      first_valid_row_idx: 1
      last_valid_row_idx: -2
      header_row_idx: 0

    variables:
      -
        name: do
        directory_path: ../../data/DO
        variable_name: HMI_DO
        metadata_id: 204
        scaling_factor: 1

      -
        name: temp
        directory_path: ../../data/Temp
        variable_name: HMI_TEMP
        metadata_id: 205
        scaling_factor: 1
  -
    name: anapro
    file_structure:
      separator: "\t"
      encoding: ISO-8859-1
      dt_format: "%Y.%m.%d  %H:%M:%S"
      time_column: Date/Time
      timezone: US/Eastern
      value_column: none
      variable_column: none
      validity_column: none
      validity_flag: 0
      first_valid_row_idx: 2
      last_valid_row_idx: -1
      header_row_idx: 1

    variables:
      -
        name: NH4-N
        directory_path: ../../data/anapro
        variable_name: NH4-N [mg/L]
        metadata_id: 1
        scaling_factor: 0.001
      -
        name: K
        directory_path: ../../data/anapro
        variable_name: K [mg/L]
        metadata_id: 2
        scaling_factor: 0.001
      -
        name: pH
        directory_path: ../../data/anapro
        variable_name: pH [pH]
        metadata_id: 3
        scaling_factor: 1
      -
        name: Temp
        directory_path: ../../data/anapro
        variable_name: Temp.
        metadata_id: 4
        scaling_factor: 1
      -
        name: TSS
        directory_path: ../../data/anapro
        variable_name: TSSeq [mg/l]
        metadata_id: 5
        scaling_factor: 0.001
      -
        name: NO3-N
        directory_path: ../../data/anapro
        variable_name: NO3-Neq [mg/l]
        metadata_id: 6
        scaling_factor: 0.001
      -
        name: COD
        directory_path: ../../data/anapro
        variable_name: CODeq [mg/l]
        metadata_id: 7
        scaling_factor: 0.001
      -
        name: CODf
        directory_path: ../../data/anapro
        variable_name: CODfeq [mg/l]
        metadata_id: 8
        scaling_factor: 0.001
